Iter1
ArtemShalinFe/gophermart pull request #1
Opened 2023-07-14 12:13 UTC by ArtemShalinFe

2023-07-14 12:51 UTC, ArtemShalinFe commented
На промежуточное ревью.
Что сделано:

- [x] Регистрация пользователя
- [x] Аутентификация пользователя
- [x] Загрузка номера заказа
- [x] Получение списка загруженных номеров заказов
- [ ] Получение текущего баланса пользователя
- [ ] Запрос на списание средств
- [ ] Получение информации о выводе средств
- [ ] Взаимодействие с системой расчёта начислений баллов лояльности

2023-07-24 15:29 UTC, s-shpak requested changes
1. Поправь, пожалуйста, ворнинги линтера

2023-07-24 15:29 UTC, s-shpak commented on go.mod
Если я запускаю сервис с помощью docker-compose, а потом вызываю `go mod tidy`, то я получаю такую ошибку:

```
github.com/ArtemShalinFe/gophermart/deployments/db/data: open /home/bp/go/src/praktikum/github.com/reviews/ArtemShalinFe/gophermart/deployments/db/data: permission denied
pattern all: open /home/bp/go/src/praktikum/github.com/reviews/ArtemShalinFe/gophermart/deployments/db/data: permission denied
```

ее надо исправить

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/mock_handlers.go
Если я перегенерирую моки при помощи `make mocks`, то тесты ломаются

2023-07-24 15:29 UTC, s-shpak commented on Makefile
>  .PHONY: lint
Не получается запустить линтер:

```
/bin/sh: 1: cannot create ./golangci-lint/report.json: Directory nonexistent
make: *** [Makefile:28: lint] Error 2
```

2023-07-24 15:29 UTC, s-shpak commented on Makefile
> -    > ./golangci-lint/report-unformatted.json | jq > ./golangci-lint/report.json | rm ./golangci-lint/report-unformatted.json
А почему ты отказался от форматирования?

2023-07-24 15:29 UTC, s-shpak commented on Makefile
> +		-v $(abspath ./deployments/db/init/):/docker-entrypoint-initdb.d \
Для того чтобы получить путь к папке, в котороый лежит `Makefile` лучше использовать такой подход: https://gist.github.com/bbl/5429c4a0a498c5ef91c10201e1b651c2

Проверь, работает ли это при вызове `Makefile` из другого `Makefile`

2023-07-24 15:29 UTC, s-shpak commented on Makefile
> +	mockgen -source=cmd/gophermart/internal/server/handlers.go -destination=cmd/gophermart/internal/server/mock_handlers.go -package server
Было бы неплохо добавить возможность удалять все сгенерированные файлы

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
Папку `internal` лучше положить в корень проекта, а не в `cmd`. В `cmd` должны лежать точки входа (и минимальная логика для работы с ними)

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/main.go
> +			if runtime.GOOS != "darwin" {
Я предполагаю, что не все ошибки стоит игнорировать. Лучше провертиь, что ошибку, которая возникла, действительно можно пропустить

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/main.go
> +		if err := log.Sync(); err != nil {
`Sync` лучше вызвать тогда, когда все компоненты завершатся. Т.е. его можно вызвать, например, после `wg.Wait`

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/main.go
> +	log.Infof("config %+v", cfg)
Здесь стоит быть осторожным, чтобы в логи не попала конфиденциальная инфа (пароли, ключи и т.п.). Подумай, как можно защититься от этого

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/main.go
> +		log.Error("failed to gracefully shutdown the service")
Смысл этой горутины как раз в том, что она убьет процесс, если мы где-то зависнем намертво. Потому `timeoutShutdown` лучше сделать подлинее (полминуты, например) и оставить `Fatal` вместо `Error`

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/server.go
> +	Log        *zap.SugaredLogger
Не совсем понимаю зачем делать это поле экспортируемым. Логгеры компонентов стоит использовать только на уровне пакета, но не выше

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/main.go
> +		if err := srv.HTTPServer.ListenAndServe(); err != nil {
`ListenAndServe`, возможно, стоит просто определить как метод `Server`

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/server.go
> +		r.Group(func(r chi.Router) {
С твоей т.з. комрессию нет смысла использовать нигде?

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/server.go
> +			case <-ctx.Done():
В случае `ctx.Done` горутину следует завершить

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/server.go
> +	ticker := time.NewTicker(time.Duration(200 * time.Millisecond))
Эту величину лучше делать конфигурируемой - в разных контекстах она может сильно варьироваться

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +    userId uuid not NULL,
Стилистическое: не стоит смешивать большие буквы и маленькие в SQL стейтментах, выбери лучше единый стиль (я советую использовать заглавные буквы, но это личное предпочтение, так что up to you)

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +    uploaded timestamp with time zone,
Почему это поле может быть `NULL`?

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +    date timestamp with time zone,
Не стоит смешивать пробелы и табуляцию

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +	userId uuid not null,
Может ли у одного пользователя быть несколько балансов?

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +CREATE TABLE Balances(
Во всех таблицах (кроме, возможно, тех, которые используются для many-to-many) лучше определять PK

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +    status VARCHAR(16) not null,
Статусы лучше определить через ENUM, чтобы не позволять записывать сюда произвольные значения

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +CREATE TABLE CurrentBalances(
См. комментарии к `Balances`

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +func CheckRetry(ctx context.Context, resp *http.Response, err error) (bool, error) {
Не стоит экспортировать

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +func Backoff(min, max time.Duration, attemptNum int, resp *http.Response) time.Duration {
Не стоит экспортировать

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +func NewAccrualClient(cfg *config.Config) *Accrual {
При инициализации сущности при помощи указателя на конфиг, стоит проверять `cfg != nil`

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +	retryClient.CheckRetry = CheckRetry
Внутри CheckRetry лучше вызвать `DefaultRetryPolicy`, которая сработает в случае проблемы соединения

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +	retryAfterString := resp.Header.Get("Retry-After")
Мне не очень нравится эта идея: если `Retry-After` достаточно большой, то `accrual client` продолжит генерировать запросы, но при этом отправляться они не будут. Их накопится много, они все вместе улетят в `accrual`, который может опять отказаься принимать запросы, и все повторится.

Лучше при получении `StatusTooManyRequests` останавливать все запросы к accrual на интервал времени = `Retry-After`

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +	req.Close = true
Почему ты добавил эту строку?

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/order.go
> +	tx, err := db.pool.Begin(ctx)
Не вижу смысла стартовать транзакцию здесь. PotgreSQL сам оборачивает единичные запросы в транзакции. Использовать их имеет смысл только если для выполнения пользовательского запроса требуется сделать несколько запросов к БД

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/order.go
> +	rows, err := tx.Query(ctx, sql, models.OrderStatusNew, models.OrderStatusProcessing)
`rows` надо закрывать

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/order.go
> +			if pgerrcode.IsIntegrityConstraintViolation(pgErr.Code) {
А как убедиться в том, что ошибка именно из-за коллизии в колонке `number`?

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/handlers.go
> +	u.Password = models.EncodePassword(u.Password)
Это никак не защищает пароль: ты просто его кодируешь. Он, по сути, все равно хранится в открытом виде. Подумай, как сделать так, чтобы если БД попадет к хакеру избежать того, чтобы пароли были скомпрометированы

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/jwt.go
> +func NewJWTToken(secretKey []byte, login string, password string) (string, error) {
Я не вижу смысла в добавлении пароля (тем более в открытом виде) в JWT

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/server.go
> +		for o := range orders {
Эта рутина тоже должна завершаться штатно

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/jwt.go
> +func IsAuthorized(tokenString string, secretKey []byte) (bool, error) {
Этот метод необязательно делать экспотируемым

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/jwt.go
> +func (h *Handlers) GetUserFromJWTToken(w http.ResponseWriter, r *http.Request) (*models.User, error) {
В принципе, ты можешь извлекать всю информацию в middleware, сохранять ее в контексте и дальше не парсить токен еще раз

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/jwt_test.go
> +func TestIsAuthorized(t *testing.T) {
Проверь на expiration

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/handlers.go
> +	h.log.Info("GetBalance not implemented")
NYI

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/server/handlers.go
> +	h.log.Info("AddBalanceWithdraw not implemented")
NYI

2023-07-24 15:29 UTC, s-shpak commented on cmd/gophermart/internal/db/user.go
> +	tx, err := db.pool.Begin(ctx)
Транзакция не нужна здесь и в других обращениях к базе, где ты посылаешь только один запрос

2023-07-24 15:30 UTC, s-shpak requested changes
1. Поправь, пожалуйста, ворнинги линтера

2023-07-27 07:36 UTC, ArtemShalinFe commented on Makefile
> +		-v $(abspath ./deployments/db/init/):/docker-entrypoint-initdb.d \
Ага, понял. `$(abspath)` - это относительно текущего каталога, а не относительно `Makefile`.

2023-07-27 09:23 UTC, ArtemShalinFe commented on cmd/gophermart/main.go
> +			if runtime.GOOS != "darwin" {
Угу, свою ошибку тут понял. Правда не совсем понимаю как понять какую именно ошибку перехватывать потому, что у меня не получается воспроизвести [проблему](https://github.com/uber-go/zap/issues/328). Добавил проверку на `os.ErrInvalid`, но не уверен, что это она.

2023-07-27 09:24 UTC, ArtemShalinFe commented on cmd/gophermart/main.go
> +		if err := log.Sync(); err != nil {
Добавил в `defer`, перед 
```Golang
defer func() {
    wg.Wait()
}()
```

2023-07-27 09:37 UTC, ArtemShalinFe commented on cmd/gophermart/main.go
> +	log.Infof("config %+v", cfg)
Добавил имплементацию интерфейса `Stringer()` для типа `Config`.

2023-07-27 10:08 UTC, ArtemShalinFe commented on cmd/gophermart/internal/server/server.go
> +	Log        *zap.SugaredLogger
Угу уже стараюсь выработать привычку все делать приватным по умолчанию.

2023-07-27 10:25 UTC, ArtemShalinFe commented on cmd/gophermart/internal/server/server.go
> +		r.Group(func(r chi.Router) {
Сделал сжатие при получении списка заказов и при получении истории списания баллов со счета

P.S. Я подумал раз тесты не требует значит не надо усложнять 😄

2023-07-27 14:27 UTC, ArtemShalinFe commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +    uploaded timestamp with time zone,
Ошибка, исправил.

2023-07-27 14:27 UTC, ArtemShalinFe commented on cmd/gophermart/internal/db/migrations/00001_init.up.sql
> +	userId uuid not null,
Таблицу переименовал, добавил uniq.

2023-07-27 17:45 UTC, ArtemShalinFe commented on Makefile
> -    > ./golangci-lint/report-unformatted.json | jq > ./golangci-lint/report.json | rm ./golangci-lint/report-unformatted.json
Почему то на маке после вызова через пайп `jq > ./golangci-lint/report.json` файл `report.json` пустой, хотя ошибки есть. Скорее всего настроил, что-то не так. И решил, чтобы не тратить время, на время отказаться от форматирования. 

Оставь пока, пожалуйста,  если останется время разберусь - самому интересно.

2023-07-27 18:02 UTC, ArtemShalinFe commented on cmd/gophermart/internal/adapters/accrual.go
> +func NewAccrualClient(cfg *config.Config) *Accrual {
[Погуглил](https://habr.com/ru/companies/otus/articles/574838/) и решил отказаться от инициализации сущности при помощи указателя. 

Я же правильно понимаю, что, если я использую указатель, то он живет в куче и занимает память, пока на него есть ссылки и пока его gc не уберет, а, если использовать копию структуры, то память освободится как только он пропадет из стека вызовов. 

То есть без крайней необходимости лучше не инициализировать сущности при помощи указателей?

2023-07-27 18:13 UTC, ArtemShalinFe commented on cmd/gophermart/internal/adapters/accrual.go
> +	req.Close = true
Я сначала думал, что это какая-то статик-проверка меня заставила, но убрал это строку и вроде никто не ругается. Значит скопировал откуда-то и забыл удалить.

Получается с этой строкой у меня каждый раз новый коннект создается, а без нее, возможно, будет переиспользоваться?

2023-07-28 13:50 UTC, ArtemShalinFe commented on cmd/gophermart/internal/adapters/accrual.go
> +	retryAfterString := resp.Header.Get("Retry-After")
Переписал. И что-то мне подсказывает, что я как обычно намудрил, но более простого решения в голову не пришло.

2023-07-31 08:03 UTC, ArtemShalinFe commented on cmd/gophermart/internal/server/server.go
> +		r.Group(func(r chi.Router) {
Добавить добавил, а тесты не проходят. 😢

2023-07-31 12:22 UTC, ArtemShalinFe commented on go.mod
Вынес в каталог /tmp/db/data, если запускается через docker compose.

2023-08-03 21:53 UTC, s-shpak requested changes

2023-08-03 21:53 UTC, s-shpak commented on go.mod
Надо обновить с помощью `go mod tidy`

2023-08-03 21:53 UTC, s-shpak commented on cmd/gophermart/internal/server/mock_handlers.go
Все равно ломаются.

Последовательность действий:
1. запускаю `make mocks`
2. запускаю `go test ./...` получаю ошибку:
```
cmd/internal/server/mock_handlers.go:12:2: missing go.sum entry for module providing package github.com/golang/mock/gomock (imported by github.com/ArtemShalinFe/gophermart/cmd/internal/server); to add:
        go get github.com/ArtemShalinFe/gophermart/cmd/internal/server
```
3. запускаю `go mod tidy`
4. запускаю `go test ./...`, получаю ошибку:
```
cmd/internal/server/handlers_test.go:24:23: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockStorage
cmd/internal/server/handlers_test.go:25:33: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockHashController
cmd/internal/server/handlers_test.go:140:23: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockStorage
cmd/internal/server/handlers_test.go:141:33: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockHashController
cmd/internal/server/handlers_test.go:243:23: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockStorage
cmd/internal/server/handlers_test.go:244:33: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockHashController
cmd/internal/server/handlers_test.go:421:23: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockStorage
cmd/internal/server/handlers_test.go:422:33: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockHashController
cmd/internal/server/handlers_test.go:539:23: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockStorage
cmd/internal/server/handlers_test.go:540:33: cannot use ctrl (variable of type *"go.uber.org/mock/gomock".Controller) as *"github.com/golang/mock/gomock".Controller value in argument to NewMockHashController
cmd/internal/server/handlers_test.go:540:33: too many errors
```

2023-08-03 21:53 UTC, s-shpak commented on Makefile
> +clean-mocks:
Ты забыл добавить .PHONY

2023-08-03 21:53 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
Это все еще не поправлено

2023-08-03 21:53 UTC, s-shpak commented on cmd/gophermart/main.go
> +			if runtime.GOOS != "darwin" {
В этом случае, пока можно оставить с текущей обавленной проверкой и поправить, когда возникнет такая необходимость

В реальных проектах - я бы почитал код zap и попробовал бы все же воспроизвести. Если бы это не получилось, то см. выше

2023-08-03 21:53 UTC, s-shpak commented on cmd/gophermart/internal/server/server.go
> +		r.Group(func(r chi.Router) {
Ок, надо разбираться с тестами, но тогда выпили пока логику компрессии, чтобы в проекте не было deadcode

2023-08-03 21:53 UTC, s-shpak commented on cmd/internal/db/migrations/00001_init.up.sql
> +    seq bigserial,
Не совсем понял, а как эта величина выставляется? Ее можно сделать автогенерируемой при помощи https://stackoverflow.com/questions/64016778/better-to-use-serial-primary-key-or-generated-always-as-identity-for-primary-key

2023-08-03 21:53 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +func NewAccrualClient(cfg *config.Config) *Accrual {
Про стек - верно, но не всегда, почитай про memory escaping: https://blog.devgenius.io/in-depth-analysis-of-golang-memory-escape-edfbfb856913

В целом, иногда копирование вместо передачи по указателю дает выигрыш, иногда нет. Надо тестировать и смотерть бенчмарки. Я советовал бы тебе просто придерживаться единого стиля в твоем приложении

2023-08-03 21:53 UTC, s-shpak commented on cmd/internal/adapters/accrual.go
> +		httpClient: &http.Client{},
А почему ты решил отказаться от retryablehttp ?

2023-08-03 21:53 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +	req.Close = true
Теоретически так, но в обычных приложениях, скорее всего, это строка ни на что не повлияет

2023-08-03 21:53 UTC, s-shpak commented on cmd/internal/server/handlers.go
> +	c, err := u.GetUserBalance(ctx, h.store)
Получать баланс и информацию по списанию баллов надо в одной транзакции

2023-08-03 21:53 UTC, s-shpak commented on cmd/gophermart/internal/adapters/accrual.go
> +	retryAfterString := resp.Header.Get("Retry-After")
В принципе, реализовано нормально. Я бы не стал разбивать на три отдельные горутины, но твоя имплементация тоже валидна (хотя она несколько более хрупкая)

2023-08-04 06:22 UTC, ArtemShalinFe commented on cmd/gophermart/internal/adapters/accrual.go
Извиняюсь, забыл. Поправил. Теперь точно.

2023-08-04 06:33 UTC, ArtemShalinFe commented on cmd/internal/adapters/accrual.go
> +		httpClient: &http.Client{},
В тот момент я подумал, раз 429 код "правильно поднять выше" значит эта библиотека не нужна. А сейчас, когда ты спросил, понимаю, что она еще и от всяких сетевых проблем "защищает" и нужно было оставить...

2023-08-04 06:43 UTC, ArtemShalinFe commented on cmd/internal/db/migrations/00001_init.up.sql
> +    seq bigserial,
На сколько я понимаю `serial` или `bigserial` - это по сути счётчик, который последовательно увеличивается. Синтаксический сахар. А в твоей статье говориться, что так лучше не делать. Переделаю.

2023-08-04 09:12 UTC, ArtemShalinFe commented on cmd/internal/adapters/accrual.go
> +		httpClient: &http.Client{},
Вернул.
Оказывается, там есть `DefaultBackoff`, который проверяет `Retry-After` в заголовке. 
А я свои костыли городил... 😄

2023-08-04 14:28 UTC, artemshalin commented on cmd/gophermart/internal/server/mock_handlers.go
Сергей, весь день потратил, чтобы понять проблему, но у меня никак не получается ее даже воспроизвести 😢. Попробовал на **MacOS** и **Windows** + **Ubuntu на WSL**.

2023-08-04 14:29 UTC, ArtemShalinFe commented on cmd/gophermart/internal/server/mock_handlers.go
Пробовал просто клонировать репозиторий и делать выше описанные действия - не получается.

2023-08-04 17:03 UTC, s-shpak commented on cmd/internal/db/migrations/00001_init.up.sql
> +    seq bigserial,
Упс, сорри, я прочитал "bigint" сначала

2023-08-04 17:09 UTC, s-shpak commented on cmd/gophermart/internal/server/mock_handlers.go
Странное поведение: gomock как будто несовместим с uber/mock

Я поразбираюсь со своей стороны, т.к. автотесты проходят, но поведение странное

2023-08-04 17:10 UTC, s-shpak approved these changes

2023-08-07 13:52 UTC, merged